/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import controler.MainController;
import java.sql.SQLException;
import view.MainScreen;

public class App {
    
    public String getGreeting() {
        return "Started Taskfy!";
    }

    public static void main(String[] args) throws SQLException {
        System.out.println(new App().getGreeting());
        
        MainScreen main = new MainScreen();
        main.setVisible(true);
        
    }
}
