/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controler.MainController;
import controler.TaskController;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Task;

/**
 *
 * @author diego
 */
public class AddTaskScreen extends javax.swing.JFrame {

    private MainController mc;
    private TaskController controller;
    private Integer idProject;
    
    private boolean update = false;
    private int index;
    
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    Task task = new Task();

    /**
     * Creates new form AddProjectScreen
     */
    public AddTaskScreen() {
        initComponents();
        
        
        setLocationRelativeTo(null);
    }

    public AddTaskScreen(MainController mc) {
        initComponents();
        this.mc = mc;
        this.controller = new TaskController(this, mc);
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpToolBar = new javax.swing.JPanel();
        jlTitle = new javax.swing.JLabel();
        btFinish = new javax.swing.JLabel();
        jpBody = new javax.swing.JPanel();
        jlName = new javax.swing.JLabel();
        jtName = new javax.swing.JTextField();
        jlDescription = new javax.swing.JLabel();
        jsDescription = new javax.swing.JScrollPane();
        jtDescription = new javax.swing.JTextPane();
        jlPrazo = new javax.swing.JLabel();
        jfDeadline = new javax.swing.JFormattedTextField();
        jlNodes = new javax.swing.JLabel();
        jsNodes = new javax.swing.JScrollPane();
        jtNodes = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(351, 548));
        setMinimumSize(new java.awt.Dimension(351, 548));
        setName("createTask"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jpToolBar.setBackground(new java.awt.Color(0, 153, 153));
        jpToolBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlTitle.setFont(new java.awt.Font("Tibetan Machine Uni", 1, 24)); // NOI18N
        jlTitle.setForeground(new java.awt.Color(255, 255, 255));
        jlTitle.setText("Tarefa");
        jlTitle.setMaximumSize(new java.awt.Dimension(370, 256));

        btFinish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finish32.png"))); // NOI18N
        btFinish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFinish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btFinishMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpToolBarLayout = new javax.swing.GroupLayout(jpToolBar);
        jpToolBar.setLayout(jpToolBarLayout);
        jpToolBarLayout.setHorizontalGroup(
            jpToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpToolBarLayout.setVerticalGroup(
            jpToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btFinish, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpBody.setBackground(new java.awt.Color(215, 252, 252));
        jpBody.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlName.setFont(new java.awt.Font("Tibetan Machine Uni", 1, 13)); // NOI18N
        jlName.setForeground(new java.awt.Color(0, 0, 0));
        jlName.setText("Nome");

        jtName.setBackground(new java.awt.Color(255, 255, 255));
        jtName.setForeground(new java.awt.Color(0, 0, 0));
        jtName.setToolTipText("Nome da tarefa");
        jtName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlDescription.setFont(new java.awt.Font("Tibetan Machine Uni", 1, 13)); // NOI18N
        jlDescription.setForeground(new java.awt.Color(0, 0, 0));
        jlDescription.setText("Descrição");

        jtDescription.setBackground(new java.awt.Color(255, 255, 255));
        jtDescription.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtDescription.setForeground(new java.awt.Color(0, 0, 0));
        jsDescription.setViewportView(jtDescription);

        jlPrazo.setFont(new java.awt.Font("Tibetan Machine Uni", 1, 13)); // NOI18N
        jlPrazo.setForeground(new java.awt.Color(0, 0, 0));
        jlPrazo.setText("Prazo");

        jfDeadline.setBackground(new java.awt.Color(255, 255, 255));
        jfDeadline.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jfDeadline.setForeground(new java.awt.Color(0, 0, 0));
        jfDeadline.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jlNodes.setFont(new java.awt.Font("Tibetan Machine Uni", 1, 13)); // NOI18N
        jlNodes.setForeground(new java.awt.Color(0, 0, 0));
        jlNodes.setText("Nodes");

        jtNodes.setBackground(new java.awt.Color(255, 255, 255));
        jtNodes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtNodes.setForeground(new java.awt.Color(0, 0, 0));
        jsNodes.setViewportView(jtNodes);

        javax.swing.GroupLayout jpBodyLayout = new javax.swing.GroupLayout(jpBody);
        jpBody.setLayout(jpBodyLayout);
        jpBodyLayout.setHorizontalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jsNodes)
                    .addComponent(jsDescription)
                    .addComponent(jtName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jfDeadline, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpBodyLayout.createSequentialGroup()
                        .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlDescription)
                            .addComponent(jlName)
                            .addComponent(jlPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNodes))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpBodyLayout.setVerticalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlPrazo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jfDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlNodes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsNodes, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFinishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFinishMouseClicked
        try {
            if (update){
                controller.update(task, jtName.getText(), jtDescription.getText(), sdf.parse(jfDeadline.getText()), jtNodes.getText());
            }else
                controller.createTask(jtName.getText(), jtDescription.getText(), jfDeadline.getText(), jtNodes.getText());
        } catch (Exception e) {
                Logger.getLogger(AddTaskScreen.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btFinishMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTaskScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTaskScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTaskScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTaskScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTaskScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btFinish;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField jfDeadline;
    private javax.swing.JLabel jlDescription;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlNodes;
    private javax.swing.JLabel jlPrazo;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JPanel jpBody;
    private javax.swing.JPanel jpToolBar;
    private javax.swing.JScrollPane jsDescription;
    private javax.swing.JScrollPane jsNodes;
    private javax.swing.JTextPane jtDescription;
    private javax.swing.JTextField jtName;
    private javax.swing.JTextPane jtNodes;
    // End of variables declaration//GEN-END:variables

    public void clear() {
        jtName.setText("");
        jtDescription.setText("");
        jfDeadline.setText("");
        jtNodes.setText("");
        update = false;
    }
    
    public void edit(Task task) {
        this.task = task;
        jtName.setText(task.getName());
        jtDescription.setText(task.getDescription());
        jfDeadline.setText(sdf.format(task.getDeadline()));
        jtNodes.setText(task.getNodes());
        update = true;
        this.index = task.getId();
    }
    
    public void Message(String text) {
        JOptionPane.showMessageDialog(rootPane, text);
    }
}
