/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controler.MainController;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Task;
import util.ButtonColumnCellRenderer;
import util.DeadlineColumnCellRenderer;
import util.TaskTableModel;

/**
 *
 * @author diego
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    MainController controller;

    AddProjectScreen createProject;
    AddTaskScreen createTask;

    TaskTableModel tasksModel;

    public MainScreen() {
        initComponents();
        this.controller = new MainController(this);
        this.createProject = new AddProjectScreen(controller);
        this.createTask = new AddTaskScreen(controller);

        initComponentsModel();

        setLocationRelativeTo(null);
    }

    public MainScreen(MainController controller) {
        initComponents();
        this.controller = controller;
        initComponentsModel();

        setLocationRelativeTo(null);
    }

    public void decortionTableTask() {

        // Customizando o header ta table de tarefas
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        jTable1.getTableHeader().setBackground(new Color(0, 153, 153));
        jTable1.getTableHeader().setForeground(new Color(255, 255, 255));
        jTable1.getTableHeader().setReorderingAllowed(false);

        jTable1.getColumnModel().getColumn(0).setMaxWidth(40);  // Complited +
        jTable1.getColumnModel().getColumn(0).setMinWidth(42);  // Complited -

        jTable1.getColumnModel().getColumn(1).setMinWidth(100);  // Nome -
        jTable1.getColumnModel().getColumn(1).setMaxWidth(150);  // Complited +

        jTable1.getColumnModel().getColumn(2).setMinWidth(150);  // Description -

        jTable1.getColumnModel().getColumn(3).setMaxWidth(80);  // Prazo +
        jTable1.getColumnModel().getColumn(3).setMinWidth(80);  // Prazo -

        jTable1.getColumnModel().getColumn(4).setMaxWidth(60);  // Edit +
        jTable1.getColumnModel().getColumn(4).setMinWidth(60);  // Edit -

        jTable1.getColumnModel().getColumn(5).setMaxWidth(60);  // Delete +
        jTable1.getColumnModel().getColumn(5).setMinWidth(60);  // Delete -

        jTable1.getColumnModel().getColumn(3).setCellRenderer(new DeadlineColumnCellRenderer());
        jTable1.getColumnModel().getColumn(4).setCellRenderer(new ButtonColumnCellRenderer("edit"));
        jTable1.getColumnModel().getColumn(5).setCellRenderer(new ButtonColumnCellRenderer("delete"));
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jpNullTasks = new javax.swing.JPanel();
        jlImgBackground = new javax.swing.JLabel();
        jlMessage = new javax.swing.JLabel();
        jlAlert = new javax.swing.JLabel();
        jpBody = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jpToolBar = new javax.swing.JPanel();
        jlTitle = new javax.swing.JLabel();
        jlSubtitle = new javax.swing.JLabel();
        jpNewProject = new javax.swing.JPanel();
        jlProject = new javax.swing.JLabel();
        btAddProject = new javax.swing.JLabel();
        jpNewTask = new javax.swing.JPanel();
        jlTask = new javax.swing.JLabel();
        btAddTask = new javax.swing.JLabel();
        jpListProject = new javax.swing.JPanel();
        jspProjects = new javax.swing.JScrollPane();
        listProject = new javax.swing.JList<>();

        jpNullTasks.setBackground(new java.awt.Color(215, 252, 252));

        jlImgBackground.setForeground(new java.awt.Color(0, 0, 0));
        jlImgBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlImgBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lists.png"))); // NOI18N

        jlMessage.setFont(new java.awt.Font("Tibetan Machine Uni", 1, 14)); // NOI18N
        jlMessage.setForeground(new java.awt.Color(0, 153, 153));
        jlMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMessage.setText("Nenhuma tarefa por aqui");

        jlAlert.setFont(new java.awt.Font("Tibetan Machine Uni", 1, 12)); // NOI18N
        jlAlert.setForeground(new java.awt.Color(102, 102, 102));
        jlAlert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlAlert.setText("clicque no botao \"+\" para criar uma nova tarefa");

        javax.swing.GroupLayout jpNullTasksLayout = new javax.swing.GroupLayout(jpNullTasks);
        jpNullTasks.setLayout(jpNullTasksLayout);
        jpNullTasksLayout.setHorizontalGroup(
            jpNullTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNullTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpNullTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlImgBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlAlert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                    .addComponent(jlMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpNullTasksLayout.setVerticalGroup(
            jpNullTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNullTasksLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlImgBackground)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1000, 520));

        jpBody.setBackground(new java.awt.Color(255, 255, 255));
        jpBody.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setBackground(new java.awt.Color(0, 153, 153));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTable1.setFont(jTable1.getFont().deriveFont(jTable1.getFont().getStyle() | java.awt.Font.BOLD));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "Diego", "atleta", "12/23/2012"},
                {null, "Sara", "atleta", "20/23/2323"},
                {null, "Fernando", "namorada", "05/07/2002"},
                {null, "Fer", "irmao", "12/09/1999"}
            },
            new String [] {
                "Title 1", "Nome", "Descrição", "Prazo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setDragEnabled(true);
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(0, 102, 102));
        jTable1.setRowHeight(40);
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(false);
        jTable1.setShowHorizontalLines(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jpBodyLayout = new javax.swing.GroupLayout(jpBody);
        jpBody.setLayout(jpBodyLayout);
        jpBodyLayout.setHorizontalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpBodyLayout.setVerticalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpToolBar.setBackground(new java.awt.Color(0, 153, 153));
        jpToolBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlTitle.setFont(new java.awt.Font("Tibetan Machine Uni", 1, 36)); // NOI18N
        jlTitle.setForeground(new java.awt.Color(255, 255, 255));
        jlTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick64.png"))); // NOI18N
        jlTitle.setText("Taskfy");
        jlTitle.setMaximumSize(new java.awt.Dimension(370, 256));

        jlSubtitle.setFont(new java.awt.Font("Tibetan Machine Uni", 1, 12)); // NOI18N
        jlSubtitle.setForeground(new java.awt.Color(255, 255, 255));
        jlSubtitle.setText("  Anote tudo, nao esqueca nada!");

        javax.swing.GroupLayout jpToolBarLayout = new javax.swing.GroupLayout(jpToolBar);
        jpToolBar.setLayout(jpToolBarLayout);
        jpToolBarLayout.setHorizontalGroup(
            jpToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpToolBarLayout.createSequentialGroup()
                .addGroup(jpToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpToolBarLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpToolBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpToolBarLayout.setVerticalGroup(
            jpToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpToolBarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlSubtitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpNewProject.setBackground(new java.awt.Color(255, 255, 255));
        jpNewProject.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlProject.setFont(new java.awt.Font("Tibetan Machine Uni", 1, 24)); // NOI18N
        jlProject.setForeground(new java.awt.Color(0, 153, 153));
        jlProject.setText("Projetos");

        btAddProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btAddProject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAddProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAddProjectMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpNewProjectLayout = new javax.swing.GroupLayout(jpNewProject);
        jpNewProject.setLayout(jpNewProjectLayout);
        jpNewProjectLayout.setHorizontalGroup(
            jpNewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNewProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlProject, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAddProject, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpNewProjectLayout.setVerticalGroup(
            jpNewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNewProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpNewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btAddProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jpNewTask.setBackground(new java.awt.Color(255, 255, 255));
        jpNewTask.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlTask.setFont(new java.awt.Font("Tibetan Machine Uni", 1, 24)); // NOI18N
        jlTask.setForeground(new java.awt.Color(0, 153, 153));
        jlTask.setText("Tarefas");

        btAddTask.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btAddTask.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAddTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAddTaskMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpNewTaskLayout = new javax.swing.GroupLayout(jpNewTask);
        jpNewTask.setLayout(jpNewTaskLayout);
        jpNewTaskLayout.setHorizontalGroup(
            jpNewTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNewTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAddTask, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpNewTaskLayout.setVerticalGroup(
            jpNewTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNewTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpNewTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAddTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpListProject.setBackground(new java.awt.Color(255, 255, 255));
        jpListProject.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        listProject.setBackground(new java.awt.Color(255, 255, 255));
        listProject.setBorder(null);
        listProject.setFont(new java.awt.Font("Tibetan Machine Uni", 1, 18)); // NOI18N
        listProject.setForeground(new java.awt.Color(0, 0, 0));
        listProject.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "item 1", "item2", "item3", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listProject.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listProject.setFixedCellHeight(50);
        listProject.setFocusCycleRoot(true);
        listProject.setSelectionBackground(new java.awt.Color(0, 153, 153));
        listProject.setSelectionForeground(new java.awt.Color(0, 102, 102));
        listProject.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listProjectValueChanged(evt);
            }
        });
        jspProjects.setViewportView(listProject);

        javax.swing.GroupLayout jpListProjectLayout = new javax.swing.GroupLayout(jpListProject);
        jpListProject.setLayout(jpListProjectLayout);
        jpListProjectLayout.setHorizontalGroup(
            jpListProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspProjects)
                .addContainerGap())
        );
        jpListProjectLayout.setVerticalGroup(
            jpListProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspProjects)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpNewProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpListProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpNewTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jpToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpNewTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpNewProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpListProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAddTaskMouseClicked
        try {
            if (controller.isThereSelectProject()) {
                createTask.clear();
                createTask.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(createProject, "Selecione um projeto");
            }
        } catch (Exception e) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btAddTaskMouseClicked

    private void btAddProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAddProjectMouseClicked
        createProject.setVisible(true);
    }//GEN-LAST:event_btAddProjectMouseClicked

    private void listProjectValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listProjectValueChanged
        controller.setProjectId(listProject.getSelectedIndex());
        controller.setTasks();
    }//GEN-LAST:event_listProjectValueChanged

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        switch (jTable1.columnAtPoint(evt.getPoint())) {
            case 0:
                controller.update(
                        jTable1.rowAtPoint(evt.getPoint()),
                        jTable1.columnAtPoint(evt.getPoint()),
                        tasksModel);
                break;
            case 4:
                createTask.edit(
                        tasksModel
                                .getTasks()
                                .get(jTable1
                                        .rowAtPoint(evt
                                                .getPoint()
                                        )
                                )
                );
                createTask.setVisible(true);
                break;
            case 5: {
                if (JOptionPane.showConfirmDialog(createProject, "Confirmar a deleção") == 0) {
                    try {
                        controller.delete(
                                jTable1.rowAtPoint(evt.getPoint()),
                                jTable1.columnAtPoint(evt.getPoint()),
                                tasksModel);
                    } catch (SQLException ex) {
                        Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            break;

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void showJTableTasks(boolean hasTasks) {
        if (hasTasks) {
            // existe tarefas

            if (jpNullTasks.isVisible()) {
                jpNullTasks.setVisible(false);
                jpBody.remove(jpNullTasks);
            }

            jpBody.add(jScrollPane1);
            jScrollPane1.setVisible(true);

            javax.swing.GroupLayout jpBodyLayout = new javax.swing.GroupLayout(jpBody);
            jpBody.setLayout(jpBodyLayout);
            jpBodyLayout.setHorizontalGroup(
                    jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(jpBodyLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                                    .addContainerGap())
            );
            jpBodyLayout.setVerticalGroup(
                    jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(jpBodyLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jScrollPane1)
                                    .addContainerGap())
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jpToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jpNewProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jpListProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jpNewTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addContainerGap())
            );

            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jpToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jpNewTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jpNewProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jpListProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addContainerGap())
            );

        } else {
            if (jScrollPane1.isVisible()) {
                jScrollPane1.setVisible(false);
                jpBody.remove(jScrollPane1);
            }

            jpBody.add(jpNullTasks);
            jpNullTasks.setVisible(true);
            jpBody.setBackground(new java.awt.Color(255, 255, 255));
            jpBody.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            jpNullTasks.setBackground(new java.awt.Color(215, 252, 252));

            jlImgBackground.setForeground(new java.awt.Color(0, 0, 0));
            jlImgBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jlImgBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lists.png"))); // NOI18N

            jlMessage.setFont(new java.awt.Font("Tibetan Machine Uni", 1, 14)); // NOI18N
            jlMessage.setForeground(new java.awt.Color(0, 153, 153));
            jlMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jlMessage.setText("Nenhuma tarefa por aqui");

            jlAlert.setFont(new java.awt.Font("Tibetan Machine Uni", 1, 12)); // NOI18N
            jlAlert.setForeground(new java.awt.Color(102, 102, 102));
            jlAlert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jlAlert.setText("clicque no botao \"+\" para criar uma nova tarefa");

            javax.swing.GroupLayout jpNullTasksLayout = new javax.swing.GroupLayout(jpNullTasks);
            jpNullTasks.setLayout(jpNullTasksLayout);
            jpNullTasksLayout.setHorizontalGroup(
                    jpNullTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpNullTasksLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jpNullTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlImgBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jlAlert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jlMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addContainerGap())
            );
            jpNullTasksLayout.setVerticalGroup(
                    jpNullTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpNullTasksLayout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlImgBackground)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jlMessage)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jlAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout jpBodyLayout = new javax.swing.GroupLayout(jpBody);
            jpBody.setLayout(jpBodyLayout);
            jpBodyLayout.setHorizontalGroup(
                    jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpBodyLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jpNullTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addContainerGap())
            );
            jpBodyLayout.setVerticalGroup(
                    jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpBodyLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jpNullTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addContainerGap())
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jpToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jpNewProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jpListProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jpNewTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addContainerGap())
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jpToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jpNewTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jpNewProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jpListProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addContainerGap())
            );
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btAddProject;
    private javax.swing.JLabel btAddTask;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlAlert;
    private javax.swing.JLabel jlImgBackground;
    private javax.swing.JLabel jlMessage;
    private javax.swing.JLabel jlProject;
    private javax.swing.JLabel jlSubtitle;
    private javax.swing.JLabel jlTask;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JPanel jpBody;
    private javax.swing.JPanel jpListProject;
    private javax.swing.JPanel jpNewProject;
    private javax.swing.JPanel jpNewTask;
    private javax.swing.JPanel jpNullTasks;
    private javax.swing.JPanel jpToolBar;
    private javax.swing.JScrollPane jspProjects;
    private javax.swing.JList<String> listProject;
    // End of variables declaration//GEN-END:variables

    public Integer getSelect() {
        return listProject.getSelectedIndex();
    }

    private void initComponentsModel() {
        tasksModel = new TaskTableModel();
        jTable1.setModel(tasksModel);
        tasksModel.setTasks(controller.updateListTask());
        showJTableTasks(!tasksModel.getTasks().isEmpty());

        decortionTableTask();
    }

    public void loadProjects(String[] item) {
        listProject.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = item;

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
    }

    public void loadTasks(List<Task> tasks) {
        initComponentsModel();
    }

}
